### ISSUE TITLE
After process death, the new active view is lost - what is the recommended solution to prevent this?

### ISSUE THREAD

**Issue by Zhuinden** [grant-park/ViewSwapper#1]
Currently just setting `.next(view)` would make this view be lost, therefore in itself, not up to feature-parity in regards to either the Activity stack or the Fragment stack.

What is the proposed solution to track the current active view and be able to restore the backstack, whose responsibility would it be?

**Comment by grant-park** [comment]
Yes, ViewSwapper is much dumber than an Activity or Fragment. There is no plan to include state management as a part of this library. Instead, you should rely on your architecture. In MVI, this could be a part of your store; in MVP, your model and presenter; in MVVM, your model and ViewModel; and so forth.

Here is a dumb example: you could have an array or stack of instantiated views in MVP or any other architecture for that matter. Using this library should only affect whether or not they rendered to the user. Any runtime data should still be present so long as the view is not garbage collected and still in your array/stack (and as long as your view lifecycle methods aren't doing anything to clobber that info of course). 

Hope this makes the use case clearer! :smile:

**Comment by Zhuinden** [comment]
You can't really parcel `Array<View>` directly to `onSaveInstanceState`, but I do see that this is delegated to *whoever is using the library* as responsibility
